### ISSUE TITLE
questions about sms integration

### ISSUE THREAD

**Issue by datatalking** [datatalking/041223-041#1]
@luzdelsol668 would state what question(s) you have about the design, layout, how-to or other typical questions about where you would normally seek via a txt or email. These issue text blocks are for deeper dive into the issue, documenting the exact problem or description of the error but also creates a trail if/when it happens again.

**Comment by luzdelsol668** [comment]
Hi, I have an idea of what you want, but please be brief in the messages in a clear way so that I understand your concerns.
I can manage the integration of sms. I will need Tiwilo's API and secret keys.
The scenario will be as follows:
1- The user enters his number.
2- We collect and send a verification code so that he confirms the code sent to him
3- The user enters the code received on your phone and confirms.

**Comment by datatalking** [comment]
@luzdelsol668 please put all replies with the @myusername so this case it would be @datatalking so that's a trigger for GitHub and we can actually get paged to handle something. Otherwise your reply is for notes or documents and by default GitHub works that if you want to notify someone on GitHub use the convention of @luzdelsol668 to mention you. =)

How familiar are you with conversational commerce?
4-We can send them an SMS menu of 3 to 5 different options.

Lets just get it to this point, if we have API access from there I can framework something that can use SQL Alchemy, Numpy and other Django friendly tools, auto documenting functions etc. =)

For now lets get the website landing page working. Latest error says "run server not available"

**Comment by luzdelsol668** [comment]
@datatalking ok, let me fix it.

**Comment by luzdelsol668** [comment]
@datatalking  I have already completed the landing page. I don't know where this error comes from. I will quickly correct this error.

**Comment by datatalking** [comment]
You say that like "poof" the code in your computer updates some global database and instantly teleports it to my computer. You need to send the code to me on here via GitHub, git pull, git commit and git push should be commands you use in linux, windows or use the GitHub desktop app.
